
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("posts/new", "Create posts")) ?>
</div>

<?php echo $this->tag->form(array("posts/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search posts</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("content", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
